stages:
  - lint
  - build_site
  - deploy

# ruff:
#   stage: lint
#   image: python:3.11-slim
#   script:
#     - pip3 install ruff
#     - ruff . --output-format gitlab; ruff format . --diff

# prettier:
#   stage: lint
#   image: node:16-slim # Use Node.js image since prettier is a Node.js tool
#   script:
#     - npm install prettier
#     - npx prettier --check . # Adjust the path as needed

include:
  - local: /site/.gitlab-ci.yml
