stages:
  - docker
  - docs

pages:
  stage: docs
  image: python:alpine

  before_script:
    - pip install mkdocs
    - pip install mkdocs-material

  script:
    - cd ./web
    - mkdocs build
    - mv site ../public
    - cd ../
  artifacts:
    paths:
      - public
  only:
    - master

docker build:
  stage: docker
  image: docker

  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - sudo systemctl start docker

  script:
    - cd ./bot
    - docker build -t registry.gitlab.com/misterbiggs/simple-telegram-bot .
    - docker push registry.gitlab.com/misterbiggs/simple-telegram-bot
