image: ubuntu:18.04

stages:
  - docs
  - docker

before_script:
  - apt install -y python3-pip
  - pip install mkdocs
  - pip install mkdocs-material

  - apt get install -y docker
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

pages:
  stage: docs

  script:
    - cd ./web
    - mkdocs build
    - mv site ../public
    - cd ../
  artifacts:
    paths:
      - public
  only:
    - master

docker build:
  stage: docker
  script:
    - cd ./bot
    - docker build -t registry.gitlab.com/misterbiggs/simple-telegram-bot .
    - docker push registry.gitlab.com/misterbiggs/simple-telegram-bot
