stages:
  - docs

pages:
  stage: docs
  image: python:alpine

  before_script:
    - pip install mkdocs
    - pip install mkdocs-material

  script:
    - cd ./web
    - mkdocs build
    - mv site ../public
    - cd ../
  artifacts:
    paths:
      - public
  only:
    - documentation
