stages:
  - lint
  - build
  - build_site
  - deploy
  - deploy_site

black:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose -- .

ruff:
  stage: lint
  # image: registry.gitlab.com/pipeline-components/ruff:latest
  image: python:3.11-slim
  script:
    - pip3 install ruff
    - ruff --output-format gitlab .


include:
  - local: /site/.gitlab-ci.yml
