image: python:alpine

before_script:
  - pip install mkdocs

  - pip install mkdocs-material

pages:
  script:
  - cd ./web
  - mkdocs build
  - mv site ../public
  artifacts:
    paths:
    - public
  only:
  - master
