version: "3"
services:
  telegram:
    build:
      context: .
      dockerfile: telegram/Dockerfile
    env_file: .env
  discord:
    build:
      context: .
      dockerfile: discord/Dockerfile
    env_file: .env
