image: python:3.11

build_mkdocs:
  stage: build_site
  script:
    - cd ./site
    - pip install -r requirements.txt
    - mkdocs build --site-dir ../public --verbose
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo "Publishing site..."
  dependencies:
    - build_mkdocs
  artifacts:
    paths:
      - public
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
