site_name: Simple Stock Bot
site_url: http://misterbiggs.gitlab.io/simple-telegram-bot
nav:
    - Home: index.md
    # - Commands: commands.md
    # - About: about.md
    # - Author's Website: https://blog.ansonbiggs.com/
    - LICENSE: LICENSE.md
theme: 'material'

repo_url: https://gitlab.com/MisterBiggs/simple-telegram-bot
repo_name: Simple Telegram Bot
site_description: A Telegram Bot for stock market Data.